### ISSUE TITLE
We can not merge our pull requests ourselfs

### ISSUE THREAD

**Issue by Konkleffke** [IntroToCode/CodeMates3_Fall23#3]
## 💬 Discussion topic

We think we can not merge a pull requests to this repository ourselfs. 

## ❗ Potential issues

How do we get the rights to do so?

## 👥 People to consult

@jainaman93 
@joewadcan

**Comment by jainaman93** [comment]
Try it now

**Comment by anya-clowers** [comment]
Issue resolved! Thanks!

**Comment by anya-clowers** [comment]
Permission granted - officially closing issue!
